Menambah fitur info gempa
probolinggo-dev/hayati-bot pull request #25
Opened 2018-03-20 14:49 UTC by mosleim

things:
1. referensi datanya dapet dari [sini](http://data.bmkg.go.id/autogempa.xml)
2. info gempanya gempa terakhir aja.
3. cara pakainya kirim aja pesan:

> /gempa

2018-03-20 14:57 UTC, consciousnessdev requested changes
File : actions/gempa/index.js
Line : 18

Why using var? :D

2018-03-21 05:31 UTC, mosleim commented
@consciousnessdev teknik yang bener gimana om?

2018-03-26 15:08 UTC, adeyahya commented on actions/gempa/index.js
> +            var data_;
pake `let` om kalo butuh variable yang mutable

2018-03-26 15:08 UTC, adeyahya requested changes
please see ^

2018-03-26 23:47 UTC, mosleim reviewed
great!
semua sudah benar.

2018-03-27 00:05 UTC, mosleim commented on actions/gempa/index.js
> +            var data_;
oh, ternyata di js ada perbedaan cara deklarasi variable berdasarkan scope ya. harap maklum, programmer C. :joy:

2018-03-27 15:00 UTC, adeyahya approved these changes

2018-03-27 15:01 UTC, merged